name: flutter_web_diary
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  firebase_auth: ^1.0.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  google_sign_in: ^4.5.9
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  rxdart: ^0.26.0
  equatable: ^2.0.0
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3
  responsive_builder: ^0.3.0
  shared_preferences: ^2.0.3

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
